/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DealIntelligenceRouteImport } from './routes/deal-intelligence'
import { Route as NegotiationRouteImport } from './routes/negotiation'
import { Route as PlanReviewRouteImport } from './routes/plan-review'
import { Route as PlansRouteImport } from './routes/plans'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DealIntelligenceRoute = DealIntelligenceRouteImport.update({
  id: '/deal-intelligence',
  path: '/deal-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const NegotiationRoute = NegotiationRouteImport.update({
  id: '/negotiation',
  path: '/negotiation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanReviewRoute = PlanReviewRouteImport.update({
  id: '/plan-review',
  path: '/plan-review',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/deal-intelligence': typeof DealIntelligenceRoute
  '/negotiation': typeof NegotiationRoute
  '/plan-review': typeof PlanReviewRoute
  '/plans': typeof PlansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/deal-intelligence': typeof DealIntelligenceRoute
  '/negotiation': typeof NegotiationRoute
  '/plan-review': typeof PlanReviewRoute
  '/plans': typeof PlansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/deal-intelligence': typeof DealIntelligenceRoute
  '/negotiation': typeof NegotiationRoute
  '/plan-review': typeof PlanReviewRoute
  '/plans': typeof PlansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/copilot'
    | '/deal-intelligence'
    | '/negotiation'
    | '/plan-review'
    | '/plans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/copilot'
    | '/deal-intelligence'
    | '/negotiation'
    | '/plan-review'
    | '/plans'
  id:
    | '__root__'
    | '/'
    | '/copilot'
    | '/deal-intelligence'
    | '/negotiation'
    | '/plan-review'
    | '/plans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopilotRoute: typeof CopilotRoute
  DealIntelligenceRoute: typeof DealIntelligenceRoute
  NegotiationRoute: typeof NegotiationRoute
  PlanReviewRoute: typeof PlanReviewRoute
  PlansRoute: typeof PlansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal-intelligence': {
      id: '/deal-intelligence'
      path: '/deal-intelligence'
      fullPath: '/deal-intelligence'
      preLoaderRoute: typeof DealIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negotiation': {
      id: '/negotiation'
      path: '/negotiation'
      fullPath: '/negotiation'
      preLoaderRoute: typeof NegotiationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-review': {
      id: '/plan-review'
      path: '/plan-review'
      fullPath: '/plan-review'
      preLoaderRoute: typeof PlanReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopilotRoute: CopilotRoute,
  DealIntelligenceRoute: DealIntelligenceRoute,
  NegotiationRoute: NegotiationRoute,
  PlanReviewRoute: PlanReviewRoute,
  PlansRoute: PlansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
